[package]
name = "htminl"
version = "0.1.0"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "In-place minification of HTML file(s)."
build = "build.rs"
publish = false

[build-dependencies]
clap = "2.33.*"

[dependencies]
hyperbuild = { path = "/tmp/hyperbuild" }

[dependencies.fyi_core]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"
default-features = false
features = [ "progress", "witcher" ]

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color", "suggestions", "vec_map", "wrap_help" ]
