[package]
name = "htminl"
version = "0.0.2"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "In-place minification of HTML file(s)."

[dependencies]
hyperbuild = { path = "/tmp/hyperbuild" }
rayon = "1.3.*"
walkdir = "2.3.*"

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color" ]
