[package]
name = "htminl"
version = "0.0.7"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "In-place minification of HTML file(s)."
build = "build.rs"

[build-dependencies]
clap = "2.33.*"

[dependencies]
hyperbuild = { path = "/tmp/hyperbuild" }
rayon = "1.3.*"

[dependencies.fyi_core]
git = "https://github.com/Blobfolio/fyi.git"
default-features = false
features = [ "progress", "witcher" ]

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color", "suggestions", "vec_map", "wrap_help" ]
