[package]
name = "htminl"
version = "0.0.4"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "In-place minification of HTML file(s)."
build = "build.rs"

[build-dependencies]
clap = "2.33.*"

[dependencies]
fyi_core = { git = "https://github.com/Blobfolio/fyi.git" }
hyperbuild = { path = "/tmp/hyperbuild" }
num-format = "0.4.0"
rayon = "1.3.*"
walkdir = "2.3.*"

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color" ]
